version: '3.8'
services: 
  webscraper:
    container_name: webscraper-container
    restart: always
    build: 
      context : .
      dockerfile : Dockerfile
    volumes:
    - .:/code
    networks:
    - webscraping-net
    ports: 
      - 8080:8080

  selenium:
    container_name: chrome-container
    image: selenium/standalone-chrome
    networks:
      - webscraping-net
    ports:
      - 4444:4444


networks:
  webscraping-net: {}
