version: '3.8'
services: 
  api:
    container_name: api-container
    command : npm run start.dev
    restart: always
    build: 
      context : ./server
      dockerfile : Dockerfile
    volumes:
    - ./server/:/usr/src/app
    - /usr/src/app/node_modules
    networks:
    - casinow-net
    ports: 
      - "8001:8001"
    depends_on: 
      - mongo


  mongo:
    container_name: mongo-backend
    image: mongo
    networks:
    - casinow-net
    ports: 
      - "27017:27017"
    volumes: 
      - apiDB:/data/db


  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-container
    command: npm start
    stdin_open: true
    tty: true
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    networks:
    - casinow-net
    depends_on:
      - api
    ports:
      - "8002:8002"
    environment: 
      - WATCHPACK_POLLING="true"
    
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: dashboard-container
    command: npm start
    stdin_open: true
    tty: true
    volumes:
      - ./dashboard/:/usr/src/app
      - /usr/src/app/node_modules
    networks:
    - casinow-net
    depends_on:
      - api
    ports:
      - "8003:8003"
    environment: 
      - WATCHPACK_POLLING="true"


volumes: 
  apiDB:
    driver : local

networks:
  casinow-net:
    driver: bridge

